#!/usr/bin/env bash
#Oh god help me
i=1
while [ "$i" -le 100 ]
do
if (( i % 3 == 0 )) && (( i % 5 == 0 ))
then 
   echo "FizzBuzz"
   (( i++ ))
elif (( i % 3 == 0 )) && [ $(( i % 5 )) -ne 0 ]
then
   echo "Fizz"
   (( i++ ))
elif (( i % 5 == 0 )) && [ $(( i % 3 )) -ne 0 ]
then 
   echo "Buzz"
   (( i++ ))
elif [ $i -gt 100 ]
then 
    break 
else
       	echo "$i"
	(( i++ ))
fi 
done

